
REFRESH MATERIALIZED VIEW txi;
REFRESH MATERIALIZED VIEW change_heuristic_data;
REFRESH MATERIALIZED VIEW output_merge;
REFRESH MATERIALIZED VIEW ringsizes;
REFRESH MATERIALIZED VIEW ringsizes_nontrivial;
REFRESH MATERIALIZED VIEW ringtime;
REFRESH MATERIALIZED VIEW xmo_keyimg;
REFRESH MATERIALIZED VIEW xmv_keyimg;